### PR TITLE
Fix movement delta time

### LINKED ISSUE #43: Rolling allows player to move through walls

### PR DESCRIPTION
**Pull request by sfarmer1**

### CODE REVIEW

File: src/game/line_of_sight/vision.rs [hunk 1]
```diff
@@ -130,7 +130,7 @@ pub fn update_visible_squares(
         if ray_start.distance(visible_squares.for_position.coordinates) < 1.0 {
             continue;
         }
-        visible_squares.for_position = *grid_position;
+        //visible_squares.for_position = *grid_position;
```
Comment (mpwoz) [inline src/game/line_of_sight/vision.rs:133]: yeah, if we want the rotating in place we could also add an angle to the cache and recompute e.g. every 15 degrees

File: src/game/movement.rs [hunk 2]
```diff
@@ -139,7 +139,7 @@ pub fn apply_movement(
             _ => 1.0,
         };
 
-        position.offset += movement.velocity * dt * roll_multi;
+        position.offset += movement.velocity * roll_multi;
         position.fix_offset_overflow();
```
Comment (mpwoz) [inline src/game/movement.rs]: I don't think this is quite right - since it'll still break movement when frame rates fluctuate

File: src/game/movement.rs [hunk 3]
```diff
@@ -128,7 +128,7 @@ pub fn apply_movement(
         // apply forces and friction
         let mut velocity = movement.velocity + force;
```
Comment (mpwoz) [inline src/game/movement.rs:119]: We should just set this directly by anything that wants to move, rather than applying acceleration * dt to it. 
```suggestion
        let mut velocity = movement.velocity;
```

**Review by mpwoz — CHANGES_REQUESTED** [review]

**Comment by mpwoz** [comment]
Fixes #43

**Review by mpwoz — APPROVED** [review]

**Comment by mpwoz** [comment]
I messed around with removing acceleration, but couldn't get it to work satisfyingly - i did add a fix  for wall collisions and you're right that that line breaks FOW, we'll have to find a diff way to optimize it
